article:
    resource: ../../src/Article/Presentation/
    type: annotation

user:
    resource: ../../src/User/Presentation/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
